name: clean_riverpod
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  uuid: ^4.5.1
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0

  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.3.3
  retrofit: ^4.9.2
  dio: ^5.9.1
  dio_http_formatter: ^3.3.1
  
  freezed_annotation: ^3.1.0
  
  json_annotation: ^4.11.0
  intl: ^0.20.2
  
  # Drift Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Share
  share_plus: ^10.1.4
  
  # Image
  image_picker: ^1.1.2
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  retrofit_generator: ^10.2.3
  json_serializable: ^6.13.0 
  freezed: ^3.2.5
  riverpod_generator: ^4.0.3
  drift_dev: ^2.18.0
  go_router_builder: ^4.2.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
